version: '3'
services:
  proxy-20004:
    command:
      - TCP4-LISTEN:20004,fork
      - TCP4:${EDGEMESH_NODE_IP}:20004
    container_name: proxy-20004
    image: bobrik/socat
    network_mode: host
    stdin_open: true
    tty: true
