apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/name: kyverno
    app: kyverno
    {{- include "kyverno-dependency.labels" . | nindent 4 }}
  name: kyverno:handle-dummy-dependnecies
rules:
  - apiGroups:
      - dummy.crd.io/v1alpha1
    resources:
      - dependencies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
