apiVersion: issue.natssecrets.crossplane.io/v1alpha1
kind: Operator
metadata:
  name: myoperator
spec:
  forProvider:
    syncAccountServer: true
    claims:
      operator:
        systemAccount: sys
        accountServerUrl: "nats://139-144-160-133.nip.io:4222"
        operatorServiceUrls:
          - nats://139-144-160-133.nip.io:4222
        strictSigningKeyUsage: false
  providerConfigRef:
    name: provider-natssecrets
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: myoperator
