# This values.yaml is intended to be used with the (as of time of writing) 1.x beta helm chart for nats
# tested with `nats-1.0.0-beta.6`

statefulSet:
  patch:
    - op: add
      path: /spec/template/spec/volumes/-
      value: { name: auth-config, configMap: { name: nats-auth-config } }
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value: { name: auth-config, mountPath: /etc/nats-config/auth/ }

config:
  merge:
    00$include: ./auth/auth.config
  jetstream:
    enabled: true
    merge:
      domain: main
    fileStore:
      enabled: true
      dir: /data/jetstream
      maxSize: 10G
    memoryStore:
      enabled: true
      maxSize: 1G
  leafnodes:
    enabled: true
    port: 7422

natsBox:
  enabled: false

reloader:
  enabled: false
