version: v2beta1
name: edgefarm-network

imports:
  - path: ./config.yaml

vars:
  CLUSTER_IP:
    command: |-
      #!/bin/bash
      set -e
      IP=$(kubectl get secrets -n default cluster-ip -o jsonpath='{.data.clusterIP}' | base64 -d)
      echo ${IP}

commands:
  help: |-
    #!/bin/bash
    set -e
    GREEN='\033[0;32m'
    BRED='\033[3;31m'
    BGREEN='\033[1;32m'
    GREY='\033[0;36m'
    BOLD='\033[1m'
    NC='\033[0m' # No Color
    echo -e "${BGREEN}Usage of ${BRED}edgefarm.network:${NC}"
    echo -e "${GREEN} EdgeFarm related commands:${NC}"
    echo -e "${BOLD}  devspace run-pipeline deploy-network                ${GREY}Deploy edgefarm-network to the cluster${NC}"
    echo -e "${BOLD}  devspace run-pipeline purge-network                 ${GREY}Delete edgefarm-network from the cluster${NC}"

functions:
  wait_for_pod: |-
    #!/bin/bash
    set -e
    echo "wait for pod $1 (ns: $2)"
    until kubectl wait --for=condition=ready pod -n $2 $1 --timeout=60s 2>/dev/null; do echo -n "." && sleep 2; done

pipelines:
  deploy-main-nats: |-
    #!/bin/bash
    set -e
    COLOR='\033[0;93m'
    NC='\033[0m'
    create_deployments nats-main

  deploy-leaf-nats: |-
    create_deployments leaf-nats

  deploy-network: |-
    #!/bin/bash
    set -e
    COLOR='\033[0;93m'
    NC='\033[0m'
    kubectl label node default-worker edgefarm.io/nats-main=true --overwrite

    create_deployments servicemonitors-crd
    create_deployments nats-main
    wait_for_pod "-l app.kubernetes.io/instance=nats-main,app.kubernetes.io/name=nats" nats
    create_deployments leaf-nats
    echo -e "${COLOR}Creating example jetstream in domain: main${NC}"
    docker run --rm \
    --entrypoint /bin/sh \
    -v $(pwd)/dev/config/example.json:/config/example.json \
    natsio/nats-box:0.13.2 \
    -c "/usr/local/bin/nats stream create \
    --config /config/example.json \
    --user ${NATS_TOKEN} \
    -s nats://${CLUSTER_IP}:4222" \
    --domain main

  purge-network: |-
    #!/bin/bash
    set -e
    COLOR='\033[0;93m'
    NC='\033[0m'
    purge_deployments nats-main
    purge_deployments leaf-nats

deployments:
  nats-main:
    helm:
      chart:
        name: nats
        repo: https://nats-io.github.io/k8s/helm/charts/
      values:
        nats:
          # externalAccess is enabled because to give access to external devices through kind port mapping
          externalAccess: true
          advertise: false
          serviceAccount:
            create: false
          jetstream:
            enabled: true
            domain: main
            fileStorage:
              size: ${MAIN_NATS_MAX_STORAGE}
        exporter:
          enabled: true
          image: natsio/prometheus-nats-exporter:latest
          pullPolicy: IfNotPresent
          serviceMonitor:
            enabled: true
        namespaceOverride: "nats"
        podDisruptionBudget:
          enabled: false
        nodeSelector: { edgefarm.io/nats-main: "true" }
        cluster:
          # cluster is disabled in local setup
          enabled: false
          #replicas: 3
          noAdvertise: true
        leafnodes:
          enabled: true
          noAdvertise: true
        natsbox:
          enabled: false
        auth:
          enabled: true
          basic:
            accounts:
              {
                SYS:
                  {
                    users: [{ user: admin, password: admin }],
                    jetstream: enabled,
                  },
                default:
                  {
                    users: [{ user: user, password: pass }],
                    jetstream: enabled,
                  },
              }
            # users:
            #   - user
            # defaultPermissions:
            #   publish: [">"]
            #   subscribe: [">"]
        system_account: SYS
    namespace: nats

  servicemonitors-crd:
    kubectl:
      manifests:
        - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.coreos.com_servicemonitors.yaml

  leaf-nats:
    namespace: nats
    helm:
      chart:
        name: leaf-nats
        path: ./charts/leaf-nats
      values:
        fullnameOverride: leaf-nats
        config:
          nats:
            host: ${CLUSTER_IP}
          targetNodeGroupLabels:
            - matchLabels:
                network.edgefarm.io/edge: ""
