apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane:provider:provider-kubernetes:system
  labels: {{- include "provider-kubernetes.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane:provider:provider-kubernetes:system
subjects:
  - kind: ServiceAccount
    name: provider-kubernetes
    namespace: crossplane-system
