apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-kubernetes
  labels: {{- include "provider-kubernetes.labels" . | nindent 4 }}
spec:
  credentials:
    source: InjectedIdentity
