apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edgenetwork-operator.name" . }}
  namespace: metacontroller
  labels:
    {{- include "edgenetwork-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "edgenetwork-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "edgenetwork-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/controller"]
          args: ["--log-level", "info"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}        