apiVersion: v1
kind: Service
metadata:
  name: edgenetwork-operator
  namespace: metacontroller
  labels:
    {{- include "edgenetwork-operator.labels" . | nindent 4 }}
spec:
  selector:
   {{- include "edgenetwork-operator.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
