apiVersion: v1
kind: ConfigMap
metadata:
  name: edgemesh-server-cfg
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-server
data:
  edgemesh-server.yaml: |
    # For more detailed configuration, please refer to: https://edgemesh.netlify.app/reference/config-items.html#edgemesh-server
    modules:
      tunnel:
        enable: true
        advertiseAddress:
          - 192.168.1.42
        security:
          enable: false
          tlsCaFile: /etc/kubeedge/ca/rootCA.crt
          tlsCertFile: /etc/kubeedge/certs/server.crt
          tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
