apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-server
  name: edgemesh-server
  namespace: kubeedge
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge
      kubeedge: edgemesh-server
  template:
    metadata:
      labels:
        k8s-app: kubeedge
        kubeedge: edgemesh-server
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      containers:
        - name: edgemesh-server
          image: kubeedge/edgemesh-server:latest
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 20004
              name: relay
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: conf
              mountPath: /etc/kubeedge/config
            - name: edgemesh
              mountPath: /etc/kubeedge/edgemesh
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: ca
              mountPath: /etc/kubeedge/ca
            - name: certs
              mountPath: /etc/kubeedge/certs
      restartPolicy: Always
      serviceAccountName: edgemesh-server
      volumes:
        - name: conf
          configMap:
            name: edgemesh-server-cfg
        - name: edgemesh
          hostPath:
            path: /etc/kubeedge/edgemesh
            type: DirectoryOrCreate
        - name: ca
          secret:
            secretName: edgemesh-ca
            items:
              - key: tls.crt
                path: rootCA.crt
              - key: tls.key
                path: rootCA.key
        - name: certs
          secret:
            secretName: edgemesh-certs
            items:
              - key: tls.crt
                path: server.crt
              - key: tls.key
                path: server.key
        - name: host-time
          hostPath:
            path: /etc/localtime
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
