apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "network-dependencies-webhook.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "network-dependencies-webhook.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "network-dependencies-webhook.name" . }}
rules:
  - apiGroups: [""]
    resources:
      - "pods"
    verbs:
      - "update"
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - "streams.network.edgefarm.io"
    resources:
      - "xstreams"
      - "xconsumers"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "issue.natssecrets.crossplane.io"
    resources:
      - "users"
      - "accounts"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "nats.crossplane.io"
    resources:
      - "providerconfigs"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "network-dependencies-webhook.name" . }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "network-dependencies-webhook.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "network-dependencies-webhook.name" . }}
  apiGroup: rbac.authorization.k8s.io