apiVersion: k3d.io/v1alpha3
kind: Simple
name: edgefarm-network
servers: 1
agents: 3
kubeAPI:
  hostPort: "50550"
image: rancher/k3s:v1.21.12-k3s1
registries:
  use:
    - registry.k3d.localhost:5000
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      # set admission plugins (e.g. for capsule)
      - arg: --kube-apiserver-arg=enable-admission-plugins=PodNodeSelector,LimitRanger,ResourceQuota,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
        nodeFilters:
          - server:*
ports:
  - port: 50080:80
    nodeFilters:
      - loadbalancer
  - port: 50443:443
    nodeFilters:
      - loadbalancer
  - port: 54222:4222
    nodeFilters:
      - server:*
      - agent:*
  - port: 57422:7422
    nodeFilters:
      - server:*
      - agent:*
  - port: 57522:7522
    nodeFilters:
      - server:*
      - agent:*
