apiVersion: v2
name: edgefarm-network
description: A Helm chart for edgefarm.network. Note that you need to have metacontroller, crossplane, vault with installed to be able to install this chart.
type: application
version: 1.0.0-beta.39
appVersion: 1.0.0-beta.39
keywords:
  - edgefarm.network
  - crd
  - metacontroller
  - crossplane
  - nats
  - credentials
sources:
  - https://github.com/edgefarm/edgefarm.network
maintainers:
  - name: Armin Schlegel
    email: armin.schlegel@gmx.de
dependencies:
  - name: provider-kubernetes-helm
    version: 1.0.0-beta.39
    repository: oci://ghcr.io/edgefarm/edgefarm.network
  - name: network-resource-info-helm
    version: 1.0.0-beta.39
    repository: oci://ghcr.io/edgefarm/edgefarm.network
  - name: network-compositions-helm
    version: 1.0.0-beta.39
    repository: oci://ghcr.io/edgefarm/edgefarm.network
  - name: network-dependencies-webhook-helm
    version: 1.0.0-beta.39
    repository: oci://ghcr.io/edgefarm/edgefarm.network
  - name: edgenetwork-operator-helm
    version: 2.4.0
    repository: oci://ghcr.io/edgefarm/edgenetwork-operator
  - name: provider-nats-helm
    version: 0.2.0-1.g106c473
    repository: oci://ghcr.io/edgefarm/provider-nats
  - name: provider-natssecrets-helm
    version: 0.2.2-1.gaba697b
    repository: oci://ghcr.io/edgefarm/provider-natssecrets
  - name: nats
    version: 1.0.0-rc.0
    repository: https://nats-io.github.io/k8s/helm/charts/
