apiVersion: v2
name: edgefarm-network
description: A Helm chart for edgefarm.network. Note that you need to have metacontroller, crossplane, vault with  installed to be able to install this chart.

type: application
version: 0.1.0
appVersion: "2.1.0"

keywords:
  - edgefarm.network
  - crd
  - metacontroller

sources:
  - https://github.com/edgefarm/edgenetwork-operator

maintainers:
  - name: Armin Schlegel
    email: armin.schlegel@gmx.de

dependencies:
  - name: provider-kubernetes
    version: 0.1.0
    repository: "file://../provider-kubernetes"
  - name: network-resource-info
    version: 0.1.0
    repository: "file://../network-resource-info"
  - name: network-compositions
    version: 0.1.0
    repository: "file://../network-compositions"
  - name: edgenetwork-operator
    version: 0.1.0
    repository: "file://../edgenetwork-operator"
  - name: nats-credentials
    version: 0.1.0
    repository: "file://../nats-credentials"
  - name: provider-nats
    version: 0.1.0
    repository: "file://../provider-nats"
  - name: provider-natssecrets
    version: 0.1.0
    repository: "file://../provider-natssecrets"
  # - name: kyverno-dependency
  #   version: 0.1.0
  #   repository: "file://../kyverno-dependency"
  - name: network-dependencies-webhook
    version: 0.1.0
    repository: "file://../network-dependencies-webhook"
  - name: nats
    version: 1.0.0-rc.0
    repository: https://nats-io.github.io/k8s/helm/charts/
