apiVersion: v1
kind: Service
metadata:
  name: network-resource-info
  namespace: crossplane-system
spec:
  selector:
    app: network-resource-info
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: ClusterIP
