apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-dependencies-webhook
  namespace: crossplane-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-dependencies-webhook
rules:
  - apiGroups: [""]
    resources:
      - "pods"
    verbs:
      - "update"
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - "streams.network.edgefarm.io"
    resources:
      - "xstreams"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-dependencies-webhook
subjects:
  - kind: ServiceAccount
    name: network-dependencies-webhook
    namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: network-dependencies-webhook
  apiGroup: rbac.authorization.k8s.io
