apiVersion: v1
kind: Service
metadata:
  name: network-dependencies-webhook
  namespace: crossplane-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
      name: https-webhook
  selector:
    app: network-dependencies-webhook
  sessionAffinity: None
  type: ClusterIP
