apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-resource-info
  namespace: crossplane-system
  labels:
    app: network-resource-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-resource-info
  template:
    metadata:
      labels:
        app: network-resource-info
    spec:
      serviceAccountName: network-resource-info
      containers:
        - name: network-resource-info
          image: ghcr.io/edgefarm/edgefarm.network/network-resource-info:1.0.0-beta.27
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
