apiVersion: v1
kind: Service
metadata:
  name: network-resource-info
  namespace: crossplane-system
spec:
  selector:
    app: network-resource-info
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  type: ClusterIP
