{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-auth-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nats-credentials.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nats-auth-config
  namespace: {{ .Values.backend.nats.authConfigmapDestination.namespace }}
  labels:
    {{- include "nats-credentials.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - get
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nats-auth-config
  namespace: {{ .Values.backend.nats.authConfigmapDestination.namespace }}
  labels:
    {{- include "nats-credentials.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nats-auth-config
subjects:
  - kind: ServiceAccount
    name: nats-auth-config
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nats-auth-config-binding
  labels:
    {{- include "nats-credentials.labels" . | nindent 4 }}  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: nats-auth-config
    namespace: {{ .Values.namespace }}
{{- end }}