{{- if .Values.backend.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: nats-auth-config-template
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nats-credentials.labels" . | nindent 4 }}
data:
  config: |-
    {
      "operator": "${OPERATOR_JWT}",
      "system_account": "${SYS_ACCOUNT_PUBLIC_KEY}",
      "resolver": {
          "type": "{{ .Values.backend.nats.resolver.config.type }}",
          "dir": "{{ .Values.backend.nats.resolver.config.dir }}",
          "allow_delete": {{ .Values.backend.nats.resolver.config.allow_delete }},
          "interval": "{{ .Values.backend.nats.resolver.config.interval }}",
          "timeout": "{{ .Values.backend.nats.resolver.config.timeout }}"
      },
      "resolver_preload": {
          "${SYS_ACCOUNT_PUBLIC_KEY}": "${SYS_ACCOUNT_JWT}"
      }
    }
{{- end }}