apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    k8s-app: vault-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: vault
  template:
    metadata:
      labels:
        k8s-app: vault
    spec:
      serviceAccount: vault
      hostNetwork: true
      containers:
        - name: vault
          image: vault:1.10.3
          command:
            [
              "vault",
              "server",
              "-dev",
              "-dev-listen-address=0.0.0.0:8200",
              "-config=/config/dev-tls-config.hcl",
            ]
          volumeMounts:
            - name: config
              mountPath: /config
            - name: certs
              mountPath: /certs
          ports:
            - containerPort: 8200
              name: http
              protocol: TCP
            - containerPort: 8400
              name: tls
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: vault-config
        - name: certs
          secret:
            secretName: vault-certs
