apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-system

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml

configMapGenerator:
  - name: vault-config
    files:
      - config/dev-tls-config.hcl
