apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: vault
  name: vault
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8200
      targetPort: http
    - name: tls
      port: 8400
      targetPort: tls
  selector:
    k8s-app: vault
