apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-naboo
  namespace: nats
  labels:
    app.kubernetes.io/name: nats-naboo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nats-naboo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nats-naboo
    spec:
      containers:
        - name: nats
          image: nats:2.9.14-alpine3.17
          imagePullPolicy: IfNotPresent
          args:
            - "-c"
            - "/etc/nats-config/nats.conf"
          volumeMounts:
            - name: nats-naboo-config
              mountPath: /etc/nats-config
          resources:
            limits:
              cpu: 1m
              memory: 1G
            requests:
              cpu: 0.5m
              memory: 256Mi
      volumes:
        - name: nats-naboo-config
          configMap:
            name: nats-naboo-config
