apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: colibri-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: linode-block-storage-retain
