apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    policies.kyverno.io/title: Add a Dependency object to track resource dependencies
    policies.kyverno.io/category: Dependency Management
    policies.kyverno.io/subject: Lifecycle Management
    policies.kyverno.io/description: >-
      Create a Dependency object for resources that declare dependencies on other objects.
      Add an ownerReference that points at the object with the dependency so that the Dependency
      gets deleted automatically when the dependent resource is deleted.
  name: add-dependency
spec:
  schemaValidation: false
  background: false
  failurePolicy: Fail
  rules:
    - generate:
        apiVersion: dummy.crds.com/v1
        kind: Dependency
        namespace: "{{request.object.metadata.name}}"
        data:
          metadata:
            labels:
              dependsOn: "{{request.object.metadata.labels.dependsOnUid}}"
            ownerReferences:
              - apiVersion: "{{request.object.apiVersion}}"
                blockOwnerDeletion: true
                kind: "{{request.kind.kind}}"
                name: "{{request.name}}"
                uid: "{{request.object.metadata.uid}}"
        name: "{{request.name}}-{{request.object.metadata.labels.dependsOnUid}}"
      match:
        any:
          - resources:
              kinds:
                - "*"
                # - User
                # - ProviderConfig
                # - XEdgeNetwork
                # - XStream
                # - XConsumer
              selector:
                matchLabels:
                  dependsOnUid: ?*
      name: check-for-dependency-annotation
      preconditions:
        any:
          - key: "{{ request.operation }}"
            operator: Equals
            value: CREATE
  validationFailureAction: enforce
