apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../../manifests/vault

secretGenerator:
  - name: vault-certs
    files:
      - tls.crt=.certs/server.crt
      - tls.key=.certs/server.key
    type: "kubernetes.io/tls"

patches:
  - ./patch-host-network.yaml
