apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - crds
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - deployment.yaml
  - daemonset.yaml
  - service.yaml
  - serviceaccount.yaml

secretGenerator:
  - name: kubeedge-certs
    files:
      - server.crt=.certs/server.crt
      - server.key=.certs/server.key
