apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
  name: cloudcore
spec:
  type: ClusterIP
  ports:
    - port: 10000
      targetPort: 10000
      name: cloudhub
    - port: 10002
      targetPort: 10002
      name: cloudhub-https
    - port: 10003
      targetPort: 10003
      name: cloudstream
    - port: 10004
      targetPort: 10004
      name: tunnelport
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
