apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
  name: cloudcore
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: iptables-manager
    kubeedge: iptables-manager
  name: iptables-manager-sa
  namespace: kubeedge
