apiVersion: v1
kind: ConfigMap
metadata:
  name: initial-nats-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
    nats.json: |-
        {
            "server_name": "TEMPLATE_NATS_DOMAIN"
            "jetstream": {
                "store_dir": "/jetstream_store",
                "domain": "TEMPLATE_NATS_DOMAIN"
            },
            "http": 8222,
            "leafnodes": {
                "remotes": [
                {
                    "url": "nats://{{ .Values.config.nats.host }}:7422",
                    "account": "default",
                    "deny_imports": [
                    "local.>"
                    ],
                    "deny_exports": [
                    "local.>"
                    ]
                }
                ]
            },
            "accounts":{
                "SYS": {
                      "users": [{"user": "admin", "password": "admin"}]
                },
                "default": {
                    "users": [{ "user": "user", "password": "pass" }],
                    "jetstream": "enabled",
                }
              }
            "authorization": {
                "default_permissions": { "publish": ">", "subscribe": ">" },
              }
        }
