apiVersion: v1
kind: ConfigMap
metadata:
  name: initial-nats-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
    nats.json: |-
        {
            "server_name": "TEMPLATE_NATS_DOMAIN"
            "jetstream": {
                "store_dir": "/store",
                "domain": "TEMPLATE_NATS_DOMAIN"
            },
            "http": 8222,
            "leafnodes": {
                "remotes": [
                {
                    "url": "nats://TEMPLATE_NATS_TOKEN@TEMPLATE_NATS_HOST:7422",
                    "deny_imports": [
                    "local.>"
                    ],
                    "deny_exports": [
                    "local.>"
                    ]
                }
                ]
            }
        }
