apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
  labels: {{- include "provider-kubernetes.labels" . | nindent 4 }}
spec:
  package: {{ .Values.provider.package }}:{{ .Values.provider.tag | default .Chart.AppVersion }}
  packagePullPolicy: {{ .Values.provider.packagePullPolicy }}
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  controllerConfigRef:
    name: provider-kubernetes
