apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-nats
  labels: {{- include "provider-nats.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.provider.replicas }}
  args: 
  {{- range $i, $v := $.Values.provider.args }}
    - {{ $v }}
  {{- end }}