apiVersion: v1
kind: ConfigMap
metadata:
  name: edgemesh-agent-cfg
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-agent
data:
  edgemesh-agent.yaml: |
    # For more detailed configuration, please refer to: https://edgemesh.netlify.app/reference/config-items.html#edgemesh-agent
    modules:
      edgeProxy:
        enable: true
      tunnel:
        enable: true
        security:
          enable: false
          tlsCaFile: /etc/kubeedge/ca/rootCA.pem
          tlsCertFile: /etc/kubeedge/certs/node.pem
          tlsPrivateKeyFile: /etc/kubeedge/certs/node.key
      edgeDNS:
        enable: true
        cacheDNS:
          enable: true
