apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: edgemesh-agent
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-agent
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge
      kubeedge: edgemesh-agent
  template:
    metadata:
      labels:
        k8s-app: kubeedge
        kubeedge: edgemesh-agent
    spec:
      hostNetwork: true
      containers:
        - name: edgemesh-agent
          securityContext:
            privileged: true
          image: kubeedge/edgemesh-agent:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: conf
              mountPath: /etc/kubeedge/config
            - name: resolv
              mountPath: /etc/resolv.conf
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: ca
              mountPath: /etc/kubeedge/ca
            - name: certs
              mountPath: /etc/kubeedge/certs
      restartPolicy: Always
      serviceAccountName: edgemesh-agent
      volumes:
        - name: conf
          configMap:
            name: edgemesh-agent-cfg
        - name: resolv
          hostPath:
            path: /etc/resolv.conf
        - name: ca
          hostPath:
            path: /etc/kubeedge/edgemesh/ca/
            type: DirectoryOrCreate
        - name: certs
          hostPath:
            path: /etc/kubeedge/edgemesh/certs
            type: DirectoryOrCreate
        - name: host-time
          hostPath:
            path: /etc/localtime
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
