group: streams.network.edgefarm.io
name: Consumer
version: v1alpha1
provider:
  baseURL: https://raw.githubusercontent.com/edgefarm/%s/%s/package/crds/%s
  name: provider-nats
  version: v0.2.0
  crd:
    file: nats.crossplane.io_consumers.yaml
    version: v1alpha1
defaultConnectionSecretName: false
patchExternalName: true
keepExternalName: true
compositions:
  - name: consumer
    provider: provider-nats
    default: true
