apiVersion: k3d.io/v1alpha3
kind: Simple
name: vault-kubernets-auth
servers: 1
agents: 1
kubeAPI:
  hostPort: "34550"
image: rancher/k3s:v1.20.12-k3s1
registries:
  use:
    - registry.k3d.localhost:5000
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      # set admission plugins (e.g. for capsule)
      - arg: --kube-apiserver-arg=enable-admission-plugins=PodNodeSelector,LimitRanger,ResourceQuota,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
        nodeFilters:
          - server:*
ports:
  - port: 40080:80
    nodeFilters:
      - loadbalancer
  - port: 40443:443
    nodeFilters:
      - loadbalancer
  - port: 48400:8400
    nodeFilters:
      - server:*
      - agent:*
  - port: 48200:8200
    nodeFilters:
      - server:*
      - agent:*
