{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.name }}
  dnsNames:
    {{ toYaml .Values.certificate.config.dnsNames | nindent 4 }}
  ipAddresses:
    {{ toYaml .Values.certificate.config.ipAddresses | nindent 4 }}
  issuerRef:
    name: {{ .Values.certificate.config.issuerRef.name }}
    kind: {{ .Values.certificate.config.issuerRef.kind }}
{{- end }}