apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certificate.config.issuerRef.name }}
spec:
{{- if .Values.certificate.config.issuerRef.secret }}
  ca:
    secretName: {{ .Values.certificate.config.issuerRef.secret }}
{{- else }}
  selfSigned: {}
{{- end }}
