{{- if .Values.storage.enabled }}
{{- if .Values.storage.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-file
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  {{ toYaml .Values.storage.persistentVolume.spec | nindent 2}}
{{- end }}
{{- end }}