apiVersion: v1
kind: Service
metadata:
  name: network-resource-info
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "network-resource-info.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "network-resource-info.selectorLabels" . | nindent 4 }}
