apiVersion: v2
name: nats-credentials
description: A Helm chart for nats-credentials - to manage the operator, sys-account and nats auth config. Note that you need to have vault with the natssecrets plugin installed to be able to install this chart.

type: application
version: 0.1.0
appVersion: "0.1.0"

keywords:
  - edgefarm.network
  - nats
  - credentials

sources:
  - https://github.com/edgefarm/edgefarm.network

maintainers:
  - name: Armin Schlegel
    email: armin.schlegel@gmx.de
