namespace: nats
operatorName: operator

core:
  enabled: true

backend:
  enabled: true
  createOperator: true
  createSysaccount: true
  nats:
    resolver:
      address: nats://nats.nats.svc:4222
      config:
        type: full
        dir: "/data/jwt"
        allow_delete: true
        interval: "2m"
        timeout: "1.9s"
    authConfigmapDestination:
      name: nats-auth-config
      namespace: nats
